# Generated by Django 4.0.2 on 2022-02-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('blogpic', models.ImageField(upload_to='blogs')),
                ('blogref', models.TextField()),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.userinfo')),
            ],
        ),
    ]
