# Generated by Django 4.0.2 on 2022-03-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmessage',
            name='date',
            field=models.CharField(default='12:34PM', max_length=25),
        ),
        migrations.AlterField(
            model_name='friendmessage',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
