# Generated by Django 4.0.2 on 2022-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_friendchatpage_remove_friendmessage_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmessage',
            name='date',
            field=models.CharField(default='10:30PM', max_length=25),
        ),
    ]
