# Generated by Django 4.0.2 on 2022-04-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_friendmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmessage',
            name='date',
            field=models.CharField(default='08:17PM', max_length=25),
        ),
    ]
