# Generated by Django 4.0.2 on 2022-03-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0001_initial'),
        ('karamel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.CharField(max_length=255)),
                ('touser', models.CharField(max_length=255)),
                ('status', models.CharField(default='requested', max_length=50)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.userinfo')),
            ],
        ),
    ]
