# Generated by Django 4.0.2 on 2022-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karamel', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='dandt',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
