# Generated by Django 4.0.2 on 2022-02-25 16:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('pic', models.ImageField(upload_to='profiles')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.userinfo')),
            ],
        ),
    ]
